name: Multiblocker
version: '1.0-SNAPSHOT'
main: me.ahtism.multiblocker.Multiblocker
description: Paper Test Plugin
api-version: '1.21'
bootstrapper: me.ahtism.multiblocker.MultiblockerBootstrap
permissions:
  multiblocker.commands:
    description: "Allows players to execute Multiblocker's commands"
    default: op